#!/usr/bin/env python3

import tomllib
import re

def parse_engines(engines_file):
  with open(engines_file, "rb") as f:
      parsed_toml = tomllib.load(f)
  engines = {}
  for engine_rule in parsed_toml['engine_rules']:
    for engine_declaration in parsed_toml[engine_rule['er_template']]:
      alias = engine_rule['er_alias'].format(alias = engine_declaration['alias'])
      url_substitutions = { key: val for key, val in engine_declaration.items() if key != 'alias'}
      url = re.sub(r'{}', '{{}}', engine_rule['er_url']).format(**url_substitutions) 
      engines[alias] = url
  return engines

def gen_rofi_rows(engines):
  return [ '<b>' + alias + '</b>&#10;<i>' + re.sub('&', '&amp;', url) + '</i>' for alias, url in engines.items() ]
